"""add admin table

Revision ID: cdb21a6ee709
Revises: 
Create Date: 2025-08-23 21:07:58.997296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb21a6ee709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'admins', ['admin_id'], ['id'], ondelete='SET NULL')
    op.add_column('customers', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'admins', ['admin_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'admins', ['admin_id'], ['id'], ondelete='SET NULL')
    op.add_column('tickets', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'admins', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'admin_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'admin_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'admin_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'admin_id')
    # ### end Alembic commands ###
